SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `t_dept`;
CREATE TABLE `t_dept` (
  `C_ID` char(32) NOT NULL  COMMENT '主键',
  `C_PID` varchar(32) DEFAULT NULL COMMENT '父节点ID',
  `C_NAME` varchar(300) DEFAULT NULL COMMENT '部门名称',
  `N_ORDER` int(11) DEFAULT NULL COMMENT '显示顺序',
  `DT_CREATETIME` datetime DEFAULT NULL COMMENT '创建日期',
  PRIMARY KEY (`C_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='部门表';



